//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"

	corev1 "k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentFileConfig) DeepCopyInto(out *AgentFileConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentFileConfig.
func (in *AgentFileConfig) DeepCopy() *AgentFileConfig {
	if in == nil {
		return nil
	}
	out := new(AgentFileConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaudeConfig) DeepCopyInto(out *ClaudeConfig) {
	*out = *in
	if in.MaxTurns != nil {
		in, out := &in.MaxTurns, &out.MaxTurns
		*out = new(int)
		**out = **in
	}
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MCPServerSecrets != nil {
		in, out := &in.MCPServerSecrets, &out.MCPServerSecrets
		*out = make([]MCPServerSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MCPTimeout != nil {
		in, out := &in.MCPTimeout, &out.MCPTimeout
		*out = new(int)
		**out = **in
	}
	if in.MaxMCPOutputTokens != nil {
		in, out := &in.MaxMCPOutputTokens, &out.MaxMCPOutputTokens
		*out = new(int)
		**out = **in
	}
	if in.StrictMCPConfig != nil {
		in, out := &in.StrictMCPConfig, &out.StrictMCPConfig
		*out = new(bool)
		**out = **in
	}
	if in.MaxBudgetUSD != nil {
		in, out := &in.MaxBudgetUSD, &out.MaxBudgetUSD
		*out = new(float64)
		**out = **in
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedTools != nil {
		in, out := &in.AllowedTools, &out.AllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisallowedTools != nil {
		in, out := &in.DisallowedTools, &out.DisallowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PersistentMode != nil {
		in, out := &in.PersistentMode, &out.PersistentMode
		*out = new(bool)
		**out = **in
	}
	if in.IncludePartialMessages != nil {
		in, out := &in.IncludePartialMessages, &out.IncludePartialMessages
		*out = new(bool)
		**out = **in
	}
	if in.NoSessionPersistence != nil {
		in, out := &in.NoSessionPersistence, &out.NoSessionPersistence
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaudeConfig.
func (in *ClaudeConfig) DeepCopy() *ClaudeConfig {
	if in == nil {
		return nil
	}
	out := new(ClaudeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlausInstance) DeepCopyInto(out *KlausInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlausInstance.
func (in *KlausInstance) DeepCopy() *KlausInstance {
	if in == nil {
		return nil
	}
	out := new(KlausInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlausInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlausInstanceList) DeepCopyInto(out *KlausInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KlausInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlausInstanceList.
func (in *KlausInstanceList) DeepCopy() *KlausInstanceList {
	if in == nil {
		return nil
	}
	out := new(KlausInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KlausInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlausInstanceSpec) DeepCopyInto(out *KlausInstanceSpec) {
	*out = *in
	if in.PersonalityRef != nil {
		in, out := &in.PersonalityRef, &out.PersonalityRef
		*out = new(PersonalityReference)
		**out = **in
	}
	in.Claude.DeepCopyInto(&out.Claude)
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]PluginReference, len(*in))
		copy(*out, *in)
	}
	if in.PluginDirs != nil {
		in, out := &in.PluginDirs, &out.PluginDirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]MCPServerReference, len(*in))
		copy(*out, *in)
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make(map[string]SkillConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.AgentFiles != nil {
		in, out := &in.AgentFiles, &out.AgentFiles
		*out = make(map[string]AgentFileConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.HookScripts != nil {
		in, out := &in.HookScripts, &out.HookScripts
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AddDirs != nil {
		in, out := &in.AddDirs, &out.AddDirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoadAdditionalDirsMemory != nil {
		in, out := &in.LoadAdditionalDirsMemory, &out.LoadAdditionalDirsMemory
		*out = new(bool)
		**out = **in
	}
	if in.Workspace != nil {
		in, out := &in.Workspace, &out.Workspace
		*out = new(WorkspaceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Muster != nil {
		in, out := &in.Muster, &out.Muster
		*out = new(MusterConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlausInstanceSpec.
func (in *KlausInstanceSpec) DeepCopy() *KlausInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(KlausInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KlausInstanceStatus) DeepCopyInto(out *KlausInstanceStatus) {
	*out = *in
	if in.LastActivity != nil {
		in, out := &in.LastActivity, &out.LastActivity
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KlausInstanceStatus.
func (in *KlausInstanceStatus) DeepCopy() *KlausInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(KlausInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerReference) DeepCopyInto(out *MCPServerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerReference.
func (in *MCPServerReference) DeepCopy() *MCPServerReference {
	if in == nil {
		return nil
	}
	out := new(MCPServerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSecret) DeepCopyInto(out *MCPServerSecret) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSecret.
func (in *MCPServerSecret) DeepCopy() *MCPServerSecret {
	if in == nil {
		return nil
	}
	out := new(MCPServerSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MusterConfig) DeepCopyInto(out *MusterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MusterConfig.
func (in *MusterConfig) DeepCopy() *MusterConfig {
	if in == nil {
		return nil
	}
	out := new(MusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTLPConfig) DeepCopyInto(out *OTLPConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTLPConfig.
func (in *OTLPConfig) DeepCopy() *OTLPConfig {
	if in == nil {
		return nil
	}
	out := new(OTLPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonalityReference) DeepCopyInto(out *PersonalityReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonalityReference.
func (in *PersonalityReference) DeepCopy() *PersonalityReference {
	if in == nil {
		return nil
	}
	out := new(PersonalityReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginReference) DeepCopyInto(out *PluginReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginReference.
func (in *PluginReference) DeepCopy() *PluginReference {
	if in == nil {
		return nil
	}
	out := new(PluginReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillConfig) DeepCopyInto(out *SkillConfig) {
	*out = *in
	if in.DisableModelInvocation != nil {
		in, out := &in.DisableModelInvocation, &out.DisableModelInvocation
		*out = new(bool)
		**out = **in
	}
	if in.UserInvocable != nil {
		in, out := &in.UserInvocable, &out.UserInvocable
		*out = new(bool)
		**out = **in
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillConfig.
func (in *SkillConfig) DeepCopy() *SkillConfig {
	if in == nil {
		return nil
	}
	out := new(SkillConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryConfig) DeepCopyInto(out *TelemetryConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(OTLPConfig)
		**out = **in
	}
	if in.MetricExportIntervalMs != nil {
		in, out := &in.MetricExportIntervalMs, &out.MetricExportIntervalMs
		*out = new(int)
		**out = **in
	}
	if in.LogsExportIntervalMs != nil {
		in, out := &in.LogsExportIntervalMs, &out.LogsExportIntervalMs
		*out = new(int)
		**out = **in
	}
	if in.LogUserPrompts != nil {
		in, out := &in.LogUserPrompts, &out.LogUserPrompts
		*out = new(bool)
		**out = **in
	}
	if in.LogToolDetails != nil {
		in, out := &in.LogToolDetails, &out.LogToolDetails
		*out = new(bool)
		**out = **in
	}
	if in.IncludeSessionID != nil {
		in, out := &in.IncludeSessionID, &out.IncludeSessionID
		*out = new(bool)
		**out = **in
	}
	if in.IncludeVersion != nil {
		in, out := &in.IncludeVersion, &out.IncludeVersion
		*out = new(bool)
		**out = **in
	}
	if in.IncludeAccountUUID != nil {
		in, out := &in.IncludeAccountUUID, &out.IncludeAccountUUID
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryConfig.
func (in *TelemetryConfig) DeepCopy() *TelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(TelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceConfig) DeepCopyInto(out *WorkspaceConfig) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceConfig.
func (in *WorkspaceConfig) DeepCopy() *WorkspaceConfig {
	if in == nil {
		return nil
	}
	out := new(WorkspaceConfig)
	in.DeepCopyInto(out)
	return out
}

// Ensure unused imports are referenced.
var (
	_ = resource.Quantity{}
	_ = metav1.Condition{}
	_ = corev1.ResourceRequirements{}
)
